export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/Auth/Login",
    REFRESH_TOKEN: "/api/Auth/RefreshToken",
    LOGOUT: "/api/Auth/Logout",
    GET_ALL_ROLES: "/api/Auth/GetAllRole",
    GET_ALL_ROLES_LIST: "/api/Auth/GetAllRoles",
    GET_ALL_PERMISSIONS: "/api/Auth/GetAllPermissions",
    GET_CURRENT_PERMISSIONS: "/api/Auth/GetCurrentPermissions",
    ASSIGN_ROLE_PERMISSIONS: "/api/Auth/AssignRolePermissions",
    CREATE_ROLE: "/api/Auth/CreateRole",
  },
  USER: {
    PROFILE: "/api/User/Profile",
    GET_ALL: "/api/User",
    GET_BY_ID: (id: string) => `/api/User/${id}`,
    CREATE: "/api/User",
    UPDATE: (id: string) => `/api/User/${id}`,
    DELETE: (id: string) => `/api/User/${id}`,
    DEACTIVE: (id: string) => `/api/User/${id}/deactive`,
  },
  QUESTION_CATEGORY: {
    GET_ALL: "/api/QuestionCategory",
    GET_BY_ID: (id: number) => `/api/QuestionCategory/${id}`,
    CREATE: "/api/QuestionCategory",
    UPDATE: (id: number) => `/api/QuestionCategory/${id}`,
    DELETE: (id: number) => `/api/QuestionCategory/${id}`,
    DEACTIVE: (id: number) => `/api/QuestionCategory/${id}/deactive`,
  },
  QUESTION: {
    GET_ALL: "/api/Question",
    GET_BY_ID: (id: number) => `/api/Question/${id}`,
    CREATE: "/api/Question",
    UPDATE: (id: number) => `/api/Question/${id}`,
    DELETE: (id: number) => `/api/Question/${id}`,
    DEACTIVE: (id: number) => `/api/Question/${id}/deactive`,
  },
  STUDENT: {
    GET_ALL: "/api/Student",
    GET_BY_ID: (id: number) => `/api/Student/${id}`,
    CREATE: "/api/Student",
    UPDATE: (id: number) => `/api/Student/${id}`,
    DELETE: (id: number) => `/api/Student/${id}`,
    DEACTIVE: (id: number) => `/api/Student/${id}/deactive`,
  },
  TEACHER: {
    GET_ALL: "/api/Teacher",
    GET_BY_ID: (id: number) => `/api/Teacher/${id}`,
    CREATE: "/api/Teacher",
    UPDATE: (id: number) => `/api/Teacher/${id}`,
    DELETE: (id: number) => `/api/Teacher/${id}`,
    DEACTIVE: (id: number) => `/api/Teacher/${id}/deactive`,
  },
  COURSE: {
    GET_ALL: "/api/Course",
    GET_BY_ID: (id: number) => `/api/Course/${id}`,
    CREATE: "/api/Course",
    UPDATE: (id: number) => `/api/Course/${id}`,
    DELETE: (id: number) => `/api/Course/${id}`,
    DEACTIVE: (id: number) => `/api/Course/${id}/deactive`,
  },
  ROOM: {
    GET_ALL: "/api/Room",
    GET_BY_ID: (id: number) => `/api/Room/${id}`,
    GET_STATS: "/api/Room/stats",
    GET_SCHEDULE: (id: number) => `/api/Room/${id}/schedule`,
    CREATE: "/api/Room",
    UPDATE: (id: number) => `/api/Room/${id}`,
    DELETE: (id: number) => `/api/Room/${id}`,
    DEACTIVE: (id: number) => `/api/Room/${id}/deactive`,
  },
  CLASS: {
    GET_ALL: "/api/Class",
    GET_BY_ID: (id: number) => `/api/Class/${id}`,
    CREATE: "/api/Class",
    UPDATE: (id: number) => `/api/Class/${id}`,
    DELETE: (id: number) => `/api/Class/${id}`,
    DEACTIVE: (id: number) => `/api/Class/${id}/deactive`,
  },
  LEARNING_MATERIAL: {
    GET_ALL: "/api/LearningMaterial",
    GET_BY_ID: (id: number) => `/api/LearningMaterial/${id}`,
    CREATE: "/api/LearningMaterial",
    UPDATE: (id: number) => `/api/LearningMaterial/${id}`,
    DELETE: (id: number) => `/api/LearningMaterial/${id}`,
    DEACTIVE: (id: number) => `/api/LearningMaterial/${id}/deactive`,
  },
};

